name: npm audit

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
# on:
#   schedule:
#     - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # lolf
      - name: install dependencies
        run: npm install

      - name: Run tests
        run: npm run test-ci
        env:
          NODE_ENV: dev

      - name: Check NPM vulnerabilities
        uses: oke-py/npm-audit-action@v1.7.1
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability
          dedupe_issues: true